
name: Azure GPU Prices Auto-Update

on:
  schedule:
    - cron: '0 0 * * *'  # midnight
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Azure GPU price fetch script
        run: python azure_fetch.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git pull --rebase

      - name: Commit and push updated filtered GPU prices
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add filtered_azure_gpu_prices.json
          git diff --cached --quiet || (
            git commit -m "🔄 Auto-update Azure GPU prices"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/jumbo2020/gpu_prices.git HEAD:main
          )
